name: Af8images
favicon: null
layout_spectrum: 0.5145
typography_spectrum: 0
title: 'Travel & lifestyle photography'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-64107808-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff7342'
    - '#0a0104'
    - '#96af91'
    - '#6e4943'
    - '#fed475'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
