name: Af8images
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: 'Travel & lifestyle photography'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-64107808-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7941e'
    - '#fbca8e'
    - '#0089d0'
    - '#bfe1f3'
    - '#085675'
  brandStrength: 0.25
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
