name: Af8images
favicon: null
layout_spectrum: 0.56885
typography_spectrum: 0
title: 'Travel & lifestyle photography'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-64107808-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00395e'
    - '#fdd590'
    - '#707976'
    - '#9eb5a3'
    - '#fcfbf9'
  brandStrength: 0
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
