name: Af8images
favicon: null
layout_spectrum: 0
typography_spectrum: 0
title: 'Travel & lifestyle photography'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-64107808-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fed993'
    - '#00365c'
    - '#6e7774'
    - '#9db5a7'
    - '#603826'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
